### PR TITLE
Fixes #354

### LINKED ISSUE #354: Spørringer sendes på nytt ved zoom/panorering
**Describe the bug**
Spørringer til wms/rasterservice etc sendes på nytt ved zoom/panorering

**To Reproduce**
1. Go to https://grunnkart.firebaseapp.com/
2. Open Developer tools and open network
3. Click in map to get pointInfo (you may have to open the Katalog first)
4. Zoom/Pan
5. Observe that network requesets are resent on zoom/pan

**Expected behavior**
Only send requests once

**Additional context**
Dette har antagelig med bbox-spørringer til api å gjøre. Foreslår å ta det ut til det kan fokuesres på å få det til å virke som det skal.

### PR DESCRIPTION
**Pull request by jarped**
## Before this PR
All pointqueries were resent on zoom/pan
## After this PR
Only send pointQueries on new point

### CODE REVIEW

File: src/Kodetre/Kodeliste/KodeContainer.js [hunk 1]
```diff
@@ -26,6 +26,7 @@ class KodeContainer extends React.Component<Props, State> {
   state = { data: {} }
 
   componentWillReceiveProps(nextProps: Object) {
+    return
```
Comment (jarped) [inline src/Kodetre/Kodeliste/KodeContainer.js]: This was unintended and should propably be removed
